# Generated by Django 4.1 on 2023-03-07 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopup', '0002_alter_shine_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shine',
            name='img',
        ),
    ]
