# Generated by Django 4.1 on 2023-03-07 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopup', '0003_remove_shine_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shine',
            old_name='prise',
            new_name='price',
        ),
    ]
